name: Mirror

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror
        uses: codewurker/gravityforms-plugin-mirror-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          license-key: ${{ secrets.GF_LICENSE_KEY }}
          plugin-basename: gravityformsturnstile/turnstile.php
